export const homeproductslist = [
  {
    id: Math.random(),
    product: "pictures/products/sig1.jpg",
    name: "Ararat",
    price: 900,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig2.jpg",
    name: "Ararat",
    price: 750,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig3.jpg",
    name: "Ararat",
    price: 750,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig4.jpg",
    name: "Ararat",
    price: 1100,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig5.png",
    name: "Vape",
    price: 1500,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig6.jpg",
    name: "Vape",
    price: 3500,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig7.jpg",
    name: "Vape",
    price: 3500,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig8.jpg",
    name: "Vape",
    price: 2000,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig9.jpg",
    name: "Armenia",
    price: 900,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig10.jpg",
    name: "Vape",
    price: 2000,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig11.jpeg",
    name: "DUNHILL",
    price: 1000,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig12.jpg",
    name: "Vape",
    price: 3500,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig13.png",
    name: "EVEREST",
    price: 700,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig14.jpg",
    name: "Vape",
    price: 2500,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig15.jpg",
    name: "Vape",
    price: 2700,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig16.jpg",
    name: "Vape",
    price: 5500,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig17.jpg",
    name: "Vape",
    price: 5000,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig18.png",
    name: "Ararat",
    price: 900,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig19.jpg",
    name: "Vape",
    price: 1500,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/sig20.png",
    name: "Vape",
    price: 2000,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Cigarette',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak1.jpg",
    name: "Bakery",
    price: 350,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak2.jpg",
    name: "Bakery Meat",
    price: 560,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak3.jpg",
    name: "Bakery Bak",
    price: 420,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak4.jpg",
    name: "Bakery sweet",
    price: 510,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak5.jpg",
    name: "Bakeryy",
    price: 520,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak6.jpg",
    name: "Bakery Kruasan",
    price: 600,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak7.jpg",
    name: "Kruasan Shok",
    price: 350,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak8.jpg",
    name: "Bakery Sweet",
    price: 1600,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak9.jpg",
    name: "Big Cruasan",
    price: 750,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak10.jpg",
    name: "Cruasan",
    price: 400,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak11.jpg",
    name: "Bakery Shok",
    price: 550,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak12.jpg",
    name: "Bakery Yam-Yam",
    price: 650,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak13.jpg",
    name: "Yam-Yam",
    price: 650,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak14.jpg",
    name: "Yam-Yam",
    price: 650,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak15.jpg",
    name: "Bakery sweet",
    price: 500,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak16.jpg",
    name: "Sweet",
    price: 750,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak17.jpg",
    name: "Sweet Cack",
    price: 4500,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/bak18.jpg",
    name: "Sweet Cack",
    price: 5000,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Bakery',
  },
  {
    id: Math.random(),
    product: "pictures/products/1.jpeg",
    name: "DORITOS SWEET CHILLI PAPPER",
    price: 650,
    data: 650,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/2.png",
    name: "DORITOS BLAZE",
    price: 700,
    data: 700,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/3.png",
    name: "HARIBO MONSTERS 160g",
    price: 500,
    data: 500,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/4.jpeg",
    name: "DORITOS SOUR CREAM FLAVOUR",
    price: 820,
    data: 820,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/5.webp",
    name: "HARIBO GOLDBEARS 175g",
    price: 650,
    data: 650,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/6.webp",
    name: "HARIBO BERRY CLOUDS 117g",
    price: 900,
    data: 900,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/7.webp",
    name: "HARIBO WATERMELON 117g",
    price: 500,
    data: 500,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/8.webp",
    name: "HARIBO SOUR STREAMERS 117g",
    price: 790,
    data: 790,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/9.webp",
    name: "HARIBO PEACHES PECHES 175g",
    price: 730,
    data: 730,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/10.Png",
    name: "DORITOS HOT CORN",
    price: 750,
    data: 750,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/11.webp",
    name: "LAYS SPICY WINGS",
    price: 500,
    data: 500,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/12.avif",
    name: "LAYS WEST INDIES",
    price: 730,
    data: 730,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/13.webp",
    name: "LAYS CHEESE",
    price: 700,
    data: 700,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/14.webp",
    name: "LAYS SPANISH TOMATO TANGO",
    price: 730,
    data: 730,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/15.png",
    name: "CHEETOS CRUNCHY",
    price: 450,
    data: 450,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/16.png",
    name: "CHEETOS CHEESE",
    price: 430,
    data: 430,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/17.png",
    name: "CHEETOS BOLITAS",
    price: 500,
    data: 500,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/18.png",
    name: "CHEETOS BUFFALO",
    price: 600,
    data: 600,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/19.png",
    name: "CHEETOS CRUNCHOS SWEET CHILLI",
    price: 500,
    data: 500,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/20.png",
    name: "CHEETOS FLAMIN HOT",
    price: 570,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Snacks",
  },
  {
    id: Math.random(),
    product: "pictures/products/beetroot.png",
    name: "BEETROOT",
    price: 200,
    data: 200,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/gourd.png",
    name: "BOTTLE GOURD",
    price: 500,
    data: 500,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/brinjal.webp",
    name: "BRINJAL",
    price: 400,
    data: 400,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/broccoli.png",
    name: "BROCCOLI",
    price: 600,
    data: 600,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/cabbage.webp",
    name: "CABBAGE",
    price: 450,
    data: 450,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/carrot.png",
    name: "CARROT",
    price: 300,
    data: 300,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/cauliflower.png",
    name: "CAULI FLOWER",
    price: 500,
    data: 500,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/Celery.png",
    name: "CELERY",
    price: 350,
    data: 350,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/corn.png",
    name: "CORN",
    price: 200,
    data: 200,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/cucumber.png",
    name: "CUCUMBER",
    price: 400,
    data: 400,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/elephantyam.png",
    name: "ELEPHANT YAM",
    price: 500,
    data: 500,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/garlic.png",
    name: "GARLIC",
    price: 730,
    data: 730,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/Ginger.png",
    name: "GINGER",
    price: 600,
    data: 600,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/greenpeas.png",
    name: "GREEN PEARS",
    price: 730,
    data: 730,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/ladysfinger.png",
    name: "LADYS FINGER",
    price: 450,
    data: 450,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/mushroom.png",
    name: "MUSH ROOM",
    price: 430,
    data: 430,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/onion.png",
    name: "ONION",
    price: 500,
    data: 500,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/onion2.png",
    name: "ONION",
    price: 600,
    data: 600,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/pepper.png",
    name: "GREEN PEPPER",
    price: 500,
    data: 500,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/potato.png",
    name: "POTATO",
    price: 570,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    product: "pictures/products/100.png",
    name: "Mars Caramel",
    price: 750,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/101.png",
    name: "Mars Fun Size",
    price: 790,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/102.png",
    name: "KIT KAT DUOS Dark Chocolate Mint",
    price: 790,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/103.png",
    name: "Kit Kat® Churro Flavored ",
    price: 850,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/104.png",
    name: "Snickers",
    price: 1100,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/105.png",
    name: "Kit Kat Minis Unwrapped",
    price: 1500,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/106.png",
    name: "Kit Kat 14 original",
    price: 1800,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/107.png",
    name: "Snickers",
    price: 250,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/108.png",
    name: "Reese's 2 Peanut Butter Cups",
    price: 950,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/109.png",
    name: "Reese's Thins Dark Chocolate ",
    price: 3800,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/114.png",
    name: "Toffee Crisp ",
    price: 760,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },

  {
    id: Math.random(),
    product: "pictures/products/117.png",
    name: "Snickers Crisp",
    price: 250,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/118.png",
    name: "Nestle Aero Strawberry",
    price: 560,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/120.png",
    name: "Milka Choco Snack Minis",
    price: 560,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/121.png",
    name: "Milka Choco Wafer",
    price: 700,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/122.png",
    name: "Oreo Frozen Dairy Dessert Sandwiches",
    price: 1850,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/125.png",
    name: "Oreo Ice Cream Sandwiches ",
    price: 650,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/127.png",
    name: "OREO Os Breakfast Cereal",
    price: 650,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/130.png",
    name: "Oreo Sour Patch ",
    price: 930,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/132.png",
    name: "Roshen Dark Chocolate ",
    price: 300,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/133.png",
    name: "Roshen Wafers Choco",
    price: 480,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/134.png",
    name: "Roshen Chocolate Bar with Peanuts",
    price: 320,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/135.png",
    name: "Roshen Mont Blanc Yellow",
    price: 4000,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/136.png",
    name: "Roshen Milky Splash Toffee",
    price: 2300,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/140.png",
    name: "Roshen Moments Milk Chocolate",
    price: 2300,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/141.png",
    name: "Candy Nut",
    price: 2300,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/142.png",
    name: "Krock Roshen",
    price: 2600,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/143.png",
    name: "Lacmi Roshen",
    price: 1050,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/145.png",
    name: "Roshen CANDY NUT NOUGAT",
    price: 3600,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/146.png",
    name: "Roshen Toffelini Toffee Candy",
    price: 1900,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/148.png",
    name: "M&M's Caramel Milk Chocolate Candy",
    price: 950,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/149.png",
    name: "M&M's Peanut",
    price: 950,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/150.png",
    name: "M&M's Peanut Butter",
    price: 950,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/151.png",
    name: "Jolly Rancher Hard Candy",
    price: 2300,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/153.png",
    name: "Skittles Original Chewy Candy",
    price: 360,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/154.png",
    name: "Skittles Tropical Chewy Candy",
    price: 360,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/155.png",
    name: "Skittles Sour Candy",
    price: 960,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/156.png",
    name: "SKITTLES Smoothies Chewy Candy",
    price: 960,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/157.png",
    name: "Life Savers 5 Flavors Gummy Candy",
    price: 1200,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/158.png",
    name: "Jelly Belly Sours Jelly Beans",
    price: 2000,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/159.png",
    name: "Jelly Belly Black Licorice Flavored",
    price: 2200,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Sweets",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea1.webp",
    name: "Lipton",
    price: 1250,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea2.png",
    name: "Lipton",
    price: 1850,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea3.png",
    name: "Lipton",
    price: 1900,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea4.png",
    name: "Lipton",
    price: 1600,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea5.png",
    name: "Lipton",
    price: 1100,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea6.png",
    name: "Lipton",
    price: 1250,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea7.png",
    name: "Lipton",
    price: 1430,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea8.png",
    name: "Lipton",
    price: 1350,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea9.png",
    name: "Lipton",
    price: 1320,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/juice1.webp",
    name: "Coca Cola",
    price: 550,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Juices",
  },
  {
    id: Math.random(),
    product: "pictures/products/juice2.png",
    name: "Coca Cola",
    price: 350,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Juices",
  },
  {
    id: Math.random(),
    product: "pictures/products/juice3.webp",
    name: "Fanta",
    price: 300,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Juices",
  },
  {
    id: Math.random(),
    product: "pictures/products/juice4.webp",
    name: "Fanta",
    price: 450,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Juices",
  },
  ,
  {
    id: Math.random(),
    product: "pictures/products/juice5.webp",
    name: "Fanta",
    price: 250,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Juices",
  },
  {
    id: Math.random(),
    product: "pictures/products/juice6.png",
    name: "Maaza",
    price: 1150,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Juices",
  },
  {
    id: Math.random(),
    product: "pictures/products/juice7.webp",
    name: "Maaza",
    price: 750,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Juices",
  },
  ,
  {
    id: Math.random(),
    product: "pictures/products/juice8.png",
    name: "Maaza",
    price: 1500,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Juices",
  },
  {
    id: Math.random(),
    product: "pictures/products/juice9.jpg",
    name: "Maaza",
    price: 800,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Juices",
  },
  {
    id: Math.random(),
    product: "pictures/products/juice10.webp",
    name: "Maaza",
    price: 750,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Juices",
  },
  ,
  {
    id: Math.random(),
    product: "pictures/products/juice11.webp",
    name: "Tropicana",
    price: 1500,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Juices",
  },
  {
    id: Math.random(),
    product: "pictures/products/juice12.webp",
    name: "Tropicana",
    price: 1150,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Juices",
  },
  {
    id: Math.random(),
    product: "pictures/products/juice13.webp",
    name: "Tropicana",
    price: 750,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Juices",
  },
  ,
  {
    id: Math.random(),
    product: "pictures/products/juice14.webp",
    name: "Tropicana",
    price: 1500,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Juices",
  },
  {
    id: Math.random(),
    product: "pictures/products/juice15.png",
    name: "Tropicana",
    price: 1150,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Juices",
  },
  {
    id: Math.random(),
    product: "pictures/products/coffee1.png",
    name: "Nescafe Gold",
    price: 3250,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Coffee",
  },
  {
    id: Math.random(),
    product: "pictures/products/coffee2.png",
    name: "Nescafe Classic",
    price: 1950,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Coffee",
  },
  {
    id: Math.random(),
    product: "pictures/products/coffee3.png",
    name: "Nescafe Original",
    price: 1730,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Coffee",
  },
  {
    id: Math.random(),
    product: "pictures/products/coffee4.png",
    name: "Nescafe Classsico",
    price: 4550,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Coffee",
  },
  {
    id: Math.random(),
    product: "pictures/products/coffee5.png",
    name: "Nescafe Gold",
    price: 2340,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Coffee",
  },
  {
    id: Math.random(),
    product: "pictures/products/coffee6.webp",
    name: "Nescafe Gold",
    price: 1750,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Coffee",
  },
  {
    id: Math.random(),
    product: "pictures/products/coffee7.png",
    name: "Nescafe Classic",
    price: 2900,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Coffee",
  },
  {
    id: Math.random(),
    product: "pictures/products/coffee8.webp",
    name: "Nescafe Classic",
    price: 1600,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Coffee",
  },
  {
    id: Math.random(),
    product: "pictures/products/coffee9.png",
    name: "Nescafe Rich Recha",
    price: 4100,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Coffee",
  },
  {
    id: Math.random(),
    product: "pictures/products/coffee10.webp",
    name: "Nescafe Classic",
    price: 2300,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Coffee",
  },
  {
    id: Math.random(),
    product: "pictures/products/coffee11.webp",
    name: "Nescafe Gold",
    price: 920,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Coffee",
  },
  {
    id: Math.random(),
    product: "pictures/products/coffee12.webp",
    name: "Nescafe Classic",
    price: 560,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Coffee",
  },
  {
    id: Math.random(),
    product: "pictures/products/coffee13.webp",
    name: "Nescafe Gold",
    price: 15000,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Coffee",
  },
  {
    id: Math.random(),
    product: "pictures/products/coffee14.png",
    name: "Nescafe Classic",
    price: 1500,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Coffee",
  },
  {
    id: Math.random(),
    product: "pictures/products/coffee15.png",
    name: "Nescafe Gold",
    price: 1250,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Coffee",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea1.webp",
    name: "Lipton",
    price: 1250,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea2.png",
    name: "Lipton",
    price: 1850,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea3.png",
    name: "Lipton",
    price: 1900,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea4.png",
    name: "Lipton",
    price: 1600,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea5.png",
    name: "Lipton",
    price: 1100,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea6.png",
    name: "Lipton",
    price: 1250,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea7.png",
    name: "Lipton",
    price: 1430,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea8.png",
    name: "Lipton",
    price: 1350,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/tea9.png",
    name: "Lipton",
    price: 1320,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Tea",
  },
  {
    id: Math.random(),
    product: "pictures/products/beer1.jpg",
    name: "PAULANER",
    price: 2200,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/beer2.png",
    name: "BROOKLYN",
    price: 900,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/beer3.jpg",
    name: "GREAT LAKES",
    price: 730,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/beer4.jpg",
    name: "MAXIMUS",
    price: 550,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/beer5.png",
    name: "AMSTEL",
    price: 640,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/beer6.webp",
    name: "CORONA",
    price: 750,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/beer7.webp",
    name: "CORONA CERO",
    price: 900,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/beer8.png",
    name: "Krombacher",
    price: 1100,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/beer9.jpg",
    name: "PAULANER",
    price: 2100,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/beer10.png",
    name: "POULANER",
    price: 2300,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/beer11.jpg",
    name: "POULANER",
    price: 920,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/beer12.jpg",
    name: "TUBORG",
    price: 560,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/champ1.jpg",
    name: "BOLLINGER",
    price: 15000,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/champ2.png",
    name: "Lourent-Perrier",
    price: 14500,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/champ3.jpg",
    name: "CHAMPAGNE",
    price: 17250,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/champ4.jpg",
    name: "COURTAGE",
    price: 18000,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/champ5.jpg",
    name: "MOET",
    price: 13550,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/champ6.jpg",
    name: "Veuve Clickquot",
    price: 22000,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/vod1.jpg",
    name: "ABSOLUT LIME",
    price: 7700,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/vod2.jpg",
    name: "BELVEDERE",
    price: 15000,
    data: 570,
    quanity: 1,
    price: 8000,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/wisk4.jpg",
    name: "GLENDRONACH",
    price: 9500,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/wisk5.png",
    name: "JACK DANIELS",
    price: 18000,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/wisk6.png",
    name: "JAMESON",
    price: 6500,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/wisk7.jpg",
    name: "Ballantines",
    price: 7000,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/wisk8.png",
    name: "JAMSON",
    price: 13000,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/wisk9.jpg",
    name: "CHIVAS REGAL",
    price: 23000,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/wisk10.jpg",
    name: "CHIVAS REGAL",
    price: 22000,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/wisk11.jpg",
    name: "JACK DANIELS",
    price: 18500,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/wisk12.jpg",
    name: "JACK DANIELS",
    price: 19000,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/wisk13.jpg",
    name: "JAMSON",
    price: 16000,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/xar1.jpg",
    name: "ALMOND",
    price: 11000,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/xar2.jpeg",
    name: "MALIBU",
    price: 12500,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/xar3.jpg",
    name: "MONIN",
    price: 14300,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/xar4.jpg",
    name: "Jagermeister",
    price: 13500,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/xar5.jpg",
    name: "MONIN",
    price: 13200,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/xar6.jpg",
    name: "WENNEKER",
    price: 16300,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/xar7.jpg",
    name: "Jagermeister",
    price: 15000,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/xar8.jpg",
    name: "Captain Morgan",
    price: 11500,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/xar9.jpg",
    name: "BACARDI",
    price: 7500,
    data: 570,
    quanity: 1,
    point: "p",
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/xar10.jpg",
    name: "SHERIDANS",
    price: 12300,
    data: 570,
    quanity: 1,
    point: "p", 
    category: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    product: "pictures/products/meat1.jpg",
    name: "Beef",
    price: 2200,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat2.jpg",
    name: "Beef Sal",
    price: 2230,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat3.jpg",
    name: "Irish pork",
    price: 1800,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat4.jpg",
    name: "Steak",
    price: 4560,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat5.jpg",
    name: "Steak M",
    price: 3750,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat6.jpg",
    name: "Beef",
    price: 2630,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat7.jpg",
    name: "Lesters Beef",
    price: 650,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat8.jpg",
    name: "Beef Bologna",
    price: 2100,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat10.png",
    name: "Beef Bol",
    price: 2800,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat11.jpg",
    name: "Beefol",
    price: 4300,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat12.jpg",
    name: "Pig",
    price: 8620,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat13.jpg",
    name: "Beef Cer",
    price: 1700,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat14.jpeg",
    name: "A Pig",
    price: 7800,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat15.jpg",
    name: "Beef 01",
    price: 1300,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat16.png",
    name: "BEEF",
    price: 1800,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat17.jpg",
    name: "BeeF",
    price: 2150,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat18.jpg",
    name: "BEef",
    price: 1940,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat19.jpg",
    name: "Beef Celo",
    price: 1400,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat21.jpg",
    name: "Beefus",
    price: 4560,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat22.jpg",
    name: "Lesters Beef",
    price: 6800,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat23.jpg",
    name: "Chorizo",
    price: 2200,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat24.jpg",
    name: "Chorizo Fabric",
    price: 2600,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  },
  {
    id: Math.random(),
    product: "pictures/products/meat25.jpg",
    name: "Chorizo",
    price: 2000,
    data: 570,
    quanity: 1,
    point: "p",
    category: 'Meat',
  }
].sort(() => Math.random() - 0.5);

export const categorieslist = [
  {
    id: Math.random(),
    picture: "pictures/categories/coffeea.webp",
    name: "Coffee",
  },{
    id: Math.random(),
    picture: "pictures/categories/teaa.webp",
    name: "Tea",
  },{
    id: Math.random(),
    picture: "pictures/categories/category1.webp",
    name: "Juices",
  },
  {
    id: Math.random(),
    picture: "pictures/categories/category2.png",
    name: "Bakery",
  },
  {
    id: Math.random(),
    picture: "pictures/categories/category3.webp",
    name: "Alcoholic drinks",
  },
  {
    id: Math.random(),
    picture: "pictures/categories/category4.webp",
    name: "Fruit & Vegetables",
  },
  {
    id: Math.random(),
    picture: "pictures/categories/category5.webp",
    name: "Snacks",
  },
  {
    id: Math.random(),
    picture: "pictures/categories/category6.png",
    name: "Sweets",
  },
  {
    id: Math.random(),
    picture: "pictures/categories/category7.webp",
    name: "Meat",
  },
  {
    id: Math.random(),
    picture: "pictures/categories/category8.png",
    name: "Cigarette",
  },
];
